name: MacOS Workflow
on: [workflow_dispatch, push]

jobs:
  build_plugin:
    name: Build Plugin
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check find
        run: which find

      - name: Check ibtool
        run: which ibtool

      - name: Check ibtool version
        run: ibtool --version

      - name: Run compile script
        run: find . -name "*.xib" -type f | awk '{sub(/.xib/,"");print}' | xargs -I % ibtool --compile %.nib %.xib
        working-directory: ./ThorTypeFilter.glyphsFilter/Contents/Resources
        
      - uses: actions/upload-artifact@v2
        with:
          name: ThorTypeFilter.glyphsFilter
          path: ./ThorTypeFilter.glyphsFilter
