name: MacOS Workflow
on: [workflow_dispatch, push]

jobs:
  build_plugin:
    name: Build Plugin
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run compile script
        run: find . -name "*.xib" -type f | awk '{sub(/.xib/,"");print}' | xargs -I % ibtool --compile %.nib %.xib
        working-directory: ./ThorTypeFilter.glyphsFilter/Contents/Resources
