name: MacOS Workflow
on: [workflow_dispatch]

jobs:
  k6_local_test:
    name: k6 local test on macos
    runs-on: macos-latest

    steps:
      - name: Run compile script
        run: ./compile.sh

