name: MacOS Workflow
on: [workflow_dispatch, push]

jobs:
  build_plugin:
    name: Build Plugin
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run compile script
        run: ./compile.sh
