name: MacOS Workflow
on: [workflow_dispatch, push]

jobs:
  build_plugin:
    name: Build Plugin
    runs-on: macos-latest

    steps:
      - name: Run compile script
        run: ls .

      - name: PWD
        run: pwd
